---
- name: "PLAY 1: TEST CODE using RESTCONF"
  hosts: LAB
  connection: local
  tasks:
    - name: "TASK 1: Get interface config with RESTCONF"
      uri:
        url: "{{ API_url }}/data/Cisco-IOS-XE-native:native/Cisco-IOS-XE-native:interface"
        user: "{{ API_user }}"
        password: "{{ API_password }}"
        method: GET
        return_content: true
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false
      register: config

    - name: "TASK 2: Ensure outputs/interface/JSON folder exists"
      file:
        path: "outputs/interface/JSON"
        state: directory
      run_once: true

    - name: "TASK 3: Ensure outputs/interface/YAML folder exists"
      file:
        path: "outputs/interface/YAML"
        state: directory
      run_once: true

    - name: "TASK 4: Write JSON to disk"
      copy:
        content: "{{ config.json | to_nice_json }}"
        dest: "outputs/interface/JSON/{{ inventory_hostname }}.json"

    - name: "TASK 5: Write YAML to disk"
      copy:
        content: "{{ config.json | to_nice_yaml }}"
        dest: "outputs/interface/YAML/{{ inventory_hostname }}.yml"
