---
- name: DYNAMIC REPORTING PART
  hosts: LAB
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
  - name: CAPTURE SHOW IP ROUTE
    ios_command:
      commands:
        - show ip interface brief
    register: output

  - name: PARSE THE RAW OUTPUT
    command_parser:
      file: "parsers/ios/show_ip_interface_brief.yml"
      content: "{{ output.stdout[0] }}"
    register: ip_interface_facts


  - name: DISPLAY THE DATA
    debug: var=ip_interface_facts