---
- name: GENERATE A REPORT
  hosts: LAB
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
  - name: CAPTURE SHOW IP INTERFACE
    ios_command:
      commands:
        - show ip interface brief
    register: output
    
  - name: PARSE THE RAW OUTPUT
    command_parser:
      file: "parsers/ios/show_ip_interface_brief.yaml"
      content: "{{ output.stdout[0] }}"

  - name: DISPLAY THE DATA
    debug: var=ip_interface_facts

  - name: save output to a file
    copy: content="{{ output.stdout[0] }}" dest="/Users/gap/Home-Lab/OUTPUT/{{ inventory_hostname }}.txt"